### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by FatmanUK** [FatmanUK/webapp#11]
Kerberos.
SQRL and GPG would also be fun.

**Comment by FatmanUK** [comment]
https://github.com/jcmturner/gokrb5
https://github.com/dpotapov/go-spnego

**Comment by athajaerel** [comment]
How might authentication with GPG work? Send a nonce, sign it, send it back, server confirms signature.
Issue: browsers can't do that. It would be very manual.
