### ISSUE TITLE
Expire sessions

### ISSUE THREAD

**Issue by FatmanUK** [FatmanUK/webapp#26]

**Comment by FatmanUK** [comment]
Could use a Callwheel.

**Comment by FatmanUK** [comment]
Timeout and expiry? Expiry is fixed, timeout is shorter but extends with each access.

**Comment by athajaerel** [comment]
Already works on the client side --- the browser correctly doesn't send expired cookies.
For the server side --- need a timeout thread per timeout per session? If either times out, delete the session token. View and login routes need to start threads to timeout the session token. One thread needs to be restartable (or kill-and-create-able) by any route.
